create database customer_behaviour

use customer_behaviour

select * from customer


--Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as total_revenue from customer 
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= ( select avg(purchase_amount) from customer) 


--Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased, round(avg(review_rating),2) as max_review_rating from customer
group by item_purchased
order by max_review_rating desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, avg(purchase_amount) as avg_amount from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status, count(customer_id) as no_of_customers,
avg(purchase_amount) as avg_revenue, sum(purchase_amount) as total_purchase from customer
group by subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased,
100*sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) as discounted
from customer
group by item_purchased
order by discounted desc

SELECT TOP 5
    item_purchased,
    100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
    / COUNT(*) AS discounted_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discounted_percentage DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with cte as (
select *, case when previous_purchases = '1' then 'New'
when previous_purchases between 2 and 10 then 'Returning' else 'Loyal' end as segment
from customer)

select segment, count(customer_id) as no_of_customer from cte
group by segment

--Q8. What are the top 3 most purchased products within each category? 
with cte as (
select category, item_purchased, count(customer_id) as no_customer,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select * from cte where item_rank <= 3

 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(*)  as repeat_buyer from customer
where previous_purchases>5
group by subscription_status


--Q10. What is the revenue contribution of each age group? 

select age_group, sum(purchase_amount) as revenue from customer
group by age_group

